
name: Arduino Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          path: ./firmware
          library-manager: update
          compliance: strict
